// シェアフォーム
export const CHANGE_PRODUCTNAME = 'CHANGE_PRODUCTNAME';
export const SET_PRODUCT_IMG_URL = 'SET_PRODUCT_IMG_URL';
export const CHANGE_DESCRIPTION = 'CHANGE_DESCRIPTION';
export const CHANGE_PRICE = 'CHANGE_PRICE';
export const CHANGE_PERIOD = 'CHANGE_PERIOD';
export const CHANGE_SHIPPING_AREA = 'CHANGE_SHIPPING_AREA';
export const CHANGE_DAYS = 'CHANGE_DAYS';
export const INITIALIZE_SHARE_FORM = 'INITIALIZE_SHARE_FORM';
// シェア情報取得
export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_DATA_SUCCESS = 'RECEIVE_DATA_SUCCESS';
export const RECEIVE_DATA_FAILED = 'RECEIVE_DATA_FAILED';
// サインアップフォーム
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_MAILADDRESS = 'CHANGE_MAILADDRESS';
export const INITIALIZE_SIGNUP_FORM = 'INITIALIZE_SIGNUP_FORM';
// サインアップのエラー取得
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
// サインインフォーム
export const CHANGE_SIGNIN_MAILADDRESS = 'CHANGE_SIGNIN_MAILADDRESS';
export const CHANGE_SIGNIN_PASSWORD = 'CHANGE_SIGNIN_PASSWORD';
export const INITIALIZE_SIGNIN_FORM = 'INITIALIZE_SIGNIN_FORM';
// サインイン成功
export const GET_USER_INFORMATION = 'GET_USER_INFORMATION';
export const TOGGLE_ISSIGNIN = 'TOGGLE_ISSIGNIN';
// プロフィールのフォーム
export const CHANGE_PROFILE_NAME = 'CHANGE_PROFILE_NAME';
export const CHANGE_PROFILE_COMMENT = 'CHANGE_PROFILE_COMMENT';
export const INITIALIZE_PROFILE_FORM = 'INITIALIZE_PROFILE_FORM';
export const SET_AVATAR_IMG = 'SET_AVATAR_IMG';
// ユーザーのシェア情報取得
export const REQUEST_USER_SHARE_INFORMATION = 'REQUEST_USER_SHARE_INFORMATION';
export const RECEIVE_USER_SHARE_INFORMATION_SUCCESS = 'RECEIVE_USER_SHARE_INFORMATION_SUCCESS';
export const RECEIVE_USER_SHARE_INFORMATION_FAILED = 'RECEIVE_USER_SHARE_INFORMATION_FAILED';
// chat
export const ADD_ROOM = 'ADD_ROOM';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_ROOMS = 'SET_ROOMS';
export const INITIALIZE_MESSAGE = 'INITIALIZE_MESSAGE';
export const SET_ROOM_USERS = 'SET_ROOM_USERS';
export const SET_ROOM_NAME = 'SET_ROOM_NAME';
export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM';

export const ON_PRESENCE_CHANGED = 'ON_PRESENCE_CHANGED';
export const SET_MESSAGES = 'SET_MESSAGES';
